/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analyze` | `/analyze`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownInputParams; } | { pathname: `/feedback/result`; params?: Router.UnknownInputParams; } | { pathname: `/apparatus/[apparatus]`, params: Router.UnknownInputParams & { apparatus: string | number; } } | { pathname: `/skills/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/analyze` | `/analyze`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownOutputParams; } | { pathname: `/feedback/result`; params?: Router.UnknownOutputParams; } | { pathname: `/apparatus/[apparatus]`, params: Router.UnknownOutputParams & { apparatus: string; } } | { pathname: `/skills/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/analyze${`?${string}` | `#${string}` | ''}` | `/analyze${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/skills${`?${string}` | `#${string}` | ''}` | `/skills${`?${string}` | `#${string}` | ''}` | `/feedback/result${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analyze` | `/analyze`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownInputParams; } | { pathname: `/feedback/result`; params?: Router.UnknownInputParams; } | `/apparatus/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/skills/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/apparatus/[apparatus]`, params: Router.UnknownInputParams & { apparatus: string | number; } } | { pathname: `/skills/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
